# Site/SEO settings
email: jake220@naver.com
permalink: /:year/:month/:day/:title/
google_analytics:

title: Lino 개발 블로그
description: 프론트엔드 개발자 Lino의 개발 블로그입니다.
url: "jake920220.github.io"
baseurl:
twitter_username:
default_img: "./assets/images/blog-banner.jpg"

# Profile settings
name: "Lino Kim"
profile_img: ""
profile: "안녕하세요 프론트엔드 개발자 Lino 입니다."
social:
  github: "https://github.com/jake920220"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 10
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
